### ISSUE TITLE
Line 9 Error

### ISSUE THREAD

**Issue by LavaB0Y** [charlypoirier/redditube#9]
I have done (as far as I know) everything from the README file but I have the 'dilemma' on how to start the actual bot, do I make an .exe file out of the index file, or do I just run in thru cmd, but the thing is that I get the error message from the right and on the left is what I 'changed' in the code. Have I done something wrong and if not how do I run it?
![aaaaaaaaaaaaa4](https://user-images.githubusercontent.com/90134588/132885966-a64b8af1-4ebc-4502-a644-caa1373a6936.PNG)

**Comment by charlypoirier** [comment]
Hello,

It looks like you're starting Redditube the wrong way.

You should run your own "index.js" file with [NodeJS](https://nodejs.org/en/) (install it if you don't have it on your computer).
To do that, you can run `node index.js` or `npm start` in a terminal (CMD).

**Comment by LavaB0Y** [comment]
I have downloaded node, in fact deleted it and downloaded it before, but if I run npm start I get missing script: start. I think messed up when running npm install redditube because I didn't run it in the folder where redditube is, and to ix that I deleted everything, but when I tried to run npm install redditube it basically says to me that it is installed somewhere else. Is there I can delete it and download it again?

**Comment by LavaB0Y** [comment]
I have downloaded node, in fact deleted it and downloaded it before, but if I run "npm start" I get "missing script: start". I think I messed up when running "npm install redditube: because I didn't run it in the folder where redditube is, and to fix that I deleted everything, but when I tried to run "npm install redditube" it basically says to me that it is installed somewhere else. Is there I can delete it and download it again?

**Comment by LavaB0Y** [comment]
This is what I get when I run "node index.js" and "npm start"
![asasasasa](https://user-images.githubusercontent.com/90134588/132988330-878cfe0d-9462-46de-8f49-bdfc914b67db.PNG)

**Comment by charlypoirier** [comment]
Hey, sorry for the late response. Just to be clear, you don't need to download Redditube from GitHub yourself, if you already installed it with `npm install redditube`.

Here are some simple steps

- Create a folder for your project
- Inside of it, run `npm install redditube`, this will download Redditube so that you can use it in your project.
- Create a JavaScript file (e.g. "index.js") and put your own code into it (e.g. [this example code](https://github.com/charlypoirier/redditube#usage))
- Finally, try running your file with `node index.js`

I hope this helps.
